# Twitter Sentiment Analysis

# 01 :Frame the Problem

#### Problem Statement Link :  https://datahack.analyticsvidhya.com/contest/practice-problem-twitter-sentiment-analysis/

Is the tweet racist or not?

# 02 :Obtain Data

### Import Statements

In [3]:
!mkdir twitter
%cd twitter
!ls


/Users/marleneprado/Documents/2019/COURSES/Github/Machine_Learning/Twitter_Sentiment_Analysis/twitter/twitter


In [4]:
#!pip install missingno
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import missingno as ms
% matplotlib inline




### Reading the Train Data

In [5]:
!wget https://www.dropbox.com/s/p8fq1p6wan2g89a/train.csv 

--2019-03-09 22:31:18--  https://www.dropbox.com/s/p8fq1p6wan2g89a/train.csv
Resolving www.dropbox.com (www.dropbox.com)... 2620:100:6017:1::a27d:201, 162.125.2.1
Connecting to www.dropbox.com (www.dropbox.com)|2620:100:6017:1::a27d:201|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/raw/p8fq1p6wan2g89a/train.csv [following]
--2019-03-09 22:31:18--  https://www.dropbox.com/s/raw/p8fq1p6wan2g89a/train.csv
Reusing existing connection to [www.dropbox.com]:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc01d86bfdb3a5d708c91209a82a.dl.dropboxusercontent.com/cd/0/inline/AcxEPLv3HsVmdoXFg1hhnEdaB-n6a-HcXTWLm9tXeh8YpZ-sNxNY4tGVw-xvnolRVL9iRizmAReKZiyr1D6I-i7MWHNPxgicfTmjxE22upBAUA/file# [following]
--2019-03-09 22:31:19--  https://uc01d86bfdb3a5d708c91209a82a.dl.dropboxusercontent.com/cd/0/inline/AcxEPLv3HsVmdoXFg1hhnEdaB-n6a-HcXTWLm9tXeh8YpZ-sNxNY4tGVw-xvnolRVL9iRizmAReKZiyr1D6I-i7MWHNPxgicfTmjxE22upBAUA/file
Resolving uc

In [6]:
!ls -l

total 6176
-rw-r--r--@ 1 marleneprado  staff  3103165 Mar  9 22:31 train.csv


In [7]:
train = pd.read_csv('train.csv')
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31962 entries, 0 to 31961
Data columns (total 3 columns):
id       31962 non-null int64
label    31962 non-null int64
tweet    31962 non-null object
dtypes: int64(2), object(1)
memory usage: 749.2+ KB


# 03 : Analyze Data

In [8]:
train.head(20)

id  label                                              tweet
0    1      0   @user when a father is dysfunctional and is s...
1    2      0  @user @user thanks for #lyft credit i can't us...
2    3      0                                bihday your majesty
3    4      0  #model   i love u take with u all the time in ...
4    5      0             factsguide: society now    #motivation
5    6      0  [2/2] huge fan fare and big talking before the...
6    7      0   @user camping tomorrow @user @user @user @use...
7    8      0  the next school year is the year for exams.ðŸ˜...
8    9      0  we won!!! love the land!!! #allin #cavs #champ...
9   10      0   @user @user welcome here !  i'm   it's so #gr...
10  11      0   ↝ #ireland consumer price index (mom) climb...
11  12      0  we are so selfish. #orlando #standwithorlando ...
12  13      0  i get to see my daddy today!!   #80days #getti...
13  14      1  @user #cnn calls #michigan middle school 'buil...
14  15      1  no comment!  in #australia   #opkillingbay #se...
15  16      0  ouch...junior is angry😐#got7 #junior #yugyo...
16  17      0  i am thankful for having a paner. #thankful #p...
17  18      1                             retweet if you agree! 
18  19      0  its #friday! 😀 smiles all around via ig use...
19  20      0  as we all know, essential oils are not made of...

In [9]:
train['label'].value_counts()

0    29720
1     2242
Name: label, dtype: int64

In [10]:
train[train['label']==1]['tweet'].head()

13    @user #cnn calls #michigan middle school 'buil...
14    no comment!  in #australia   #opkillingbay #se...
17                               retweet if you agree! 
23      @user @user lumpy says i am a . prove it lumpy.
34    it's unbelievable that in the 21st century we'...
Name: tweet, dtype: object

## Label types
-   0 : Normal
-   1 : Hate

# 05 : Model Selection ( 1st Iteration)

## RandomForest without Preprocessing of Text Data

In [11]:
#Building the model without preprocessing of data
unprocessed_data = pd.read_csv('train.csv')

In [12]:
from sklearn.model_selection import train_test_split


#splitting the data into random train and test subsets
X_train, X_test, y_train, y_test = train_test_split(unprocessed_data["tweet"],
                                                        unprocessed_data["label"], 
                                                    test_size = 0.2, random_state = 42)

In [13]:
# Sequentialization of tasks
from sklearn.pipeline import Pipeline

#generating ngrams and tokens and Bagging
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer, TfidfVectorizer

from sklearn.ensemble import RandomForestClassifier

text_clf = Pipeline([('vect', CountVectorizer(stop_words='english')),
                      ('tfidf', TfidfTransformer()),
                     ('clf', RandomForestClassifier(n_estimators=50)),])

In [14]:
model = text_clf.fit(X_train,y_train)

In [15]:
predicted = model.predict(X_test)

In [16]:
from sklearn.metrics import precision_score,recall_score,f1_score, accuracy_score, confusion_matrix

In [17]:
confusion_matrix(y_test,predicted)

array([[5910,   27],
       [ 248,  208]])

In [18]:
accuracy_score(y_test,predicted)

0.9569842014703582

In [19]:
precision_score(y_test,predicted)

0.8851063829787233

In [20]:
recall_score(y_test,predicted)

0.45614035087719296

In [21]:
f1_score(y_test,predicted)

0.602026049204052

# 04 and 05 : Feature Engineering and Model Selection (2nd Iteration)

Preprocessing of Text data is very important for Textual Analysis. Tokenization, Feature Extraction (Vectorization) are the most important techniques in Scikit-Learn. 
The text must be parsed to extract words, called tokenization. Then the words need to be encoded as integers or floating point values for use as input to a machine learning algorithm, called feature extraction (or vectorization).


In [22]:
#regular expression 
import re 

#regular expression for the removal of name tags and the emoticons from tweets.
def process_tweet(tweet):
    return " ".join(re.sub("(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])", " ",tweet.lower()).split())

In [23]:
#Dropping of columns from pd
def drop_features(features,data):
    data.drop(features,inplace=True,axis=1)

In [24]:
#Applying the Process_tweet function to the given Train Data
train['processed_tweets'] = train['tweet'].apply(process_tweet)

In [25]:
train.head()

id  label                                              tweet  \
0   1      0   @user when a father is dysfunctional and is s...   
1   2      0  @user @user thanks for #lyft credit i can't us...   
2   3      0                                bihday your majesty   
3   4      0  #model   i love u take with u all the time in ...   
4   5      0             factsguide: society now    #motivation   

                                    processed_tweets  
0  when a father is dysfunctional and is so selfi...  
1  thanks for lyft credit i can t use cause they ...  
2                                bihday your majesty  
3      model i love u take with u all the time in ur  
4                  factsguide society now motivation

In [26]:
train[train['label']==1].head(20)

id  label                                              tweet  \
13    14      1  @user #cnn calls #michigan middle school 'buil...   
14    15      1  no comment!  in #australia   #opkillingbay #se...   
17    18      1                             retweet if you agree!    
23    24      1    @user @user lumpy says i am a . prove it lumpy.   
34    35      1  it's unbelievable that in the 21st century we'...   
56    57      1            @user lets fight against  #love #peace    
68    69      1  😩the white establishment can't have blk fol...   
77    78      1  @user hey, white people: you can call people '...   
82    83      1  how the #altright uses  &amp; insecurity to lu...   
111  112      1  @user i'm not interested in a #linguistics tha...   
114  115      1  @user why not @user mocked obama for being bla...   
131  132      1  #people aren't protesting #trump because a #re...   
151  152      1  yes it's  when you call #michelleobama a goril...   
156  157      1  as the smaller hands show, barry probably lied...   
167  168      1  @user @user you point one finger @user million...   
192  193      1  you might be a libtard if... #libtard  #sjw #l...   
210  211      1  @user take out the #trash america...  - i vote...   
232  233      1  if you hold open a door for a woman because sh...   
263  264      1  @user this man ran for governor of ny, the sta...   
264  265      1  #stereotyping #prejudice  offer no #hope or so...   

                                      processed_tweets  
13   cnn calls michigan middle school build the wal...  
14   no comment in australia opkillingbay seashephe...  
17                                retweet if you agree  
23                    lumpy says i am a prove it lumpy  
34   it s unbelievable that in the 21st century we ...  
56                       lets fight against love peace  
68   the white establishment can t have blk folx ru...  
77   hey white people you can call people white by ...  
82   how the altright uses amp insecurity to lure m...  
111  i m not interested in a linguistics that doesn...  
114        why not mocked obama for being black brexit  
131  people aren t protesting trump because a repub...  
151  yes it s when you call michelleobama a gorilla...  
156  as the smaller hands show barry probably lied ...  
167  you point one finger millions are pointed righ...  
192  you might be a libtard if libtard sjw liberal ...  
210  take out the trash america i voted against hat...  
232  if you hold open a door for a woman because sh...  
263  this man ran for governor of ny the state with...  
264  stereotyping prejudice offer no hope or soluti...

In [27]:
drop_features(['id','tweet'],train)

In [28]:
train.head()

label                                   processed_tweets
0      0  when a father is dysfunctional and is so selfi...
1      0  thanks for lyft credit i can t use cause they ...
2      0                                bihday your majesty
3      0      model i love u take with u all the time in ur
4      0                  factsguide society now motivation

In [29]:
#splitting the data into random train and test subsets
x_train, x_test, y_train, y_test = train_test_split(train["processed_tweets"],train["label"],
                                                    test_size = 0.2, random_state = 42)

Pipeline : Sequentially apply a list of transforms and a final estimator. Intermediate steps of the pipeline must be ‘transforms’, that is, they must implement fit and transform methods. The final estimator only needs to implement fit. 

In [30]:
text_clf = Pipeline([('vect', CountVectorizer(stop_words='english')),
                      ('tfidf', TfidfTransformer()),
                     ('clf', RandomForestClassifier(n_estimators=200)),])
text = text_clf.fit(x_train,y_train)

In [31]:
predicted = text.predict(x_test)

In [32]:
from sklearn.metrics import confusion_matrix, classification_report,precision_score

In [33]:
cm_m = confusion_matrix(y_test,predicted)
cm_m

array([[5898,   39],
       [ 225,  231]])

In [34]:
TN, FP = cm_m[0]
FN, TP = cm_m[1]

In [35]:
TP

231

In [36]:
float(TN+TP)/(TN+TP+FN+FP)

0.9587048334115439

In [37]:
p = TP/(TP+FP)
p

0.8555555555555555

In [38]:
precision_score(y_test,predicted)

0.8555555555555555

In [39]:
r = TP/(FN+TP)
r

0.506578947368421

In [40]:
recall_score(y_test,predicted)

0.506578947368421

In [41]:
f1 = 2*p*r/(p+r)
f1

0.6363636363636364

In [42]:
f1_score(y_test,predicted)

0.6363636363636364

# 04 and 05 : Feature Engineering and Model Selection (3rd Iteration)

In [43]:

count_vect = CountVectorizer(stop_words='english',ngram_range=(1,2),analyzer='word')
transformer = TfidfTransformer(norm='l2',sublinear_tf=True)

In [44]:
#splitting the data into random train and test subsets
x_train, x_test, y_train, y_test = train_test_split(train["processed_tweets"],train["label"],
                                                    test_size = 0.2, random_state = 42)

x_train_counts = count_vect.fit_transform(x_train)
x_train_tfidf = transformer.fit_transform(x_train_counts)
x_test_counts = count_vect.transform(x_test)
x_test_tfidf = transformer.transform(x_test_counts)

In [45]:
print(x_train_counts.shape)
print(x_train_tfidf.shape)
print(x_test_counts.shape)
print(x_test_tfidf.shape)

(25569, 155348)
(25569, 155348)
(6393, 155348)
(6393, 155348)


In [46]:
from sklearn.linear_model import SGDClassifier

model = SGDClassifier(loss="modified_huber", penalty="l1")
model.fit(x_train_tfidf,y_train)
predictions = model.predict(x_test_tfidf)

/Users/marleneprado/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)


In [47]:
f1_score(y_test,predictions)

0.5798212005108557

In [48]:
recall_score(y_test,predictions)

0.49780701754385964

In [49]:
precision_score(y_test,predictions)

0.6941896024464832

In [50]:
f1_score(y_test,predictions)

0.5798212005108557

# 05 : Model Selection

In [51]:
#different classification modesls being used
from sklearn.svm import LinearSVC

model_svc = LinearSVC(C=2.0,max_iter=500,tol=0.0001,loss ='hinge')
model_svc.fit(x_train_counts,y_train)

LinearSVC(C=2.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='hinge', max_iter=500, multi_class='ovr',
     penalty='l2', random_state=None, tol=0.0001, verbose=0)

In [52]:
predict_svc = model_svc.predict(x_test_counts)

In [53]:
f1_score(y_test,predict_svc)

0.6830530401034929

In [54]:
recall_score(y_test,predict_svc)

0.5789473684210527

# 06 : Tune the Model

In [55]:

#optimizing parameters
from sklearn.model_selection import GridSearchCV


params = {"tfidf__ngram_range": [(1, 2), (1,3)],
          "svc__C": [.01, .1, 1, 10, 100]}

clf = Pipeline([("tfidf", TfidfVectorizer(sublinear_tf=True)),
                ("svc", LinearSVC(loss='hinge'))])

gs = GridSearchCV(clf, params, verbose=2, n_jobs=-1)
gs.fit(x_train,y_train)
print("Best Estimator = ", gs.best_estimator_)
print("Best Score = ",gs.best_score_)

Fitting 3 folds for each of 10 candidates, totalling 30 fits


/Users/marleneprado/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 12 concurrent workers.
[Parallel(n_jobs=-1)]: Done  23 out of  30 | elapsed:   19.1s remaining:    5.8s
[Parallel(n_jobs=-1)]: Done  30 out of  30 | elapsed:   25.4s finished


Best Estimator =  Pipeline(memory=None,
     steps=[('tfidf', TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.float64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 2), norm='l2', preprocessor=None, smooth_idf=True,...e', max_iter=1000, multi_class='ovr',
     penalty='l2', random_state=None, tol=0.0001, verbose=0))])
Best Score =  0.9630411826821542


In [56]:
predicted = gs.predict(x_test)


In [57]:
predicted

array([0, 0, 0, ..., 0, 0, 1])

In [58]:
f1_score(y_test,predicted)

0.7245657568238213

In [59]:
recall_score(y_test,predicted)

0.6403508771929824

In [60]:
precision_score(y_test,predicted)

0.8342857142857143

# 07 : Predict on new cases

In [61]:
!wget https://www.dropbox.com/s/as2y6lpjsh6284l/test.csv

--2019-03-09 22:34:14--  https://www.dropbox.com/s/as2y6lpjsh6284l/test.csv
Resolving www.dropbox.com (www.dropbox.com)... 2620:100:6017:1::a27d:201, 162.125.2.1
Connecting to www.dropbox.com (www.dropbox.com)|2620:100:6017:1::a27d:201|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/raw/as2y6lpjsh6284l/test.csv [following]
--2019-03-09 22:34:14--  https://www.dropbox.com/s/raw/as2y6lpjsh6284l/test.csv
Reusing existing connection to [www.dropbox.com]:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uce1f518351b66b28c3d3bfb3eff.dl.dropboxusercontent.com/cd/0/inline/AczGFx4O5PzaYWyCZYbQiDkYiUNwWaZnzORzyrapYnj7lAjX09w_zuNp8gH41HwaOFpHM9CDwXGdd1c4YNJgwWVZUI60vBtmFYJ2ThfM1hYKqg/file# [following]
--2019-03-09 22:34:15--  https://uce1f518351b66b28c3d3bfb3eff.dl.dropboxusercontent.com/cd/0/inline/AczGFx4O5PzaYWyCZYbQiDkYiUNwWaZnzORzyrapYnj7lAjX09w_zuNp8gH41HwaOFpHM9CDwXGdd1c4YNJgwWVZUI60vBtmFYJ2ThfM1hYKqg/file
Resolving uce1f

In [62]:
submission = pd.read_csv('test.csv')
submission.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17197 entries, 0 to 17196
Data columns (total 2 columns):
id       17197 non-null int64
tweet    17197 non-null object
dtypes: int64(1), object(1)
memory usage: 268.8+ KB


In [63]:
submission['processed_tweet'] = submission['tweet'].apply(process_tweet)

In [64]:
submission.head()

id                                              tweet  \
0  31963  #studiolife #aislife #requires #passion #dedic...   
1  31964   @user #white #supremacists want everyone to s...   
2  31965  safe ways to heal your #acne!!    #altwaystohe...   
3  31966  is the hp and the cursed child book up for res...   
4  31967    3rd #bihday to my amazing, hilarious #nephew...   

                                     processed_tweet  
0  studiolife aislife requires passion dedication...  
1  white supremacists want everyone to see the ne...  
2  safe ways to heal your acne altwaystoheal heal...  
3  is the hp and the cursed child book up for res...  
4  3rd bihday to my amazing hilarious nephew eli ...

In [65]:
drop_features(['tweet'],submission)

In [66]:
submission.head()

id                                    processed_tweet
0  31963  studiolife aislife requires passion dedication...
1  31964  white supremacists want everyone to see the ne...
2  31965  safe ways to heal your acne altwaystoheal heal...
3  31966  is the hp and the cursed child book up for res...
4  31967  3rd bihday to my amazing hilarious nephew eli ...

In [67]:
predicted = gs.predict(submission['processed_tweet'])

In [68]:
predicted

array([0, 0, 0, ..., 0, 0, 0])

In [69]:
final_predict = pd.DataFrame(predicted,columns=['label'])
result = pd.DataFrame(submission['id'],columns=['id'])
result = pd.concat([result,final_predict],axis=1)
result.to_csv('final_predictions.csv',index=False)

In [70]:
result['label'].value_counts()

0    16247
1      950
Name: label, dtype: int64